spring.application.name=clinicapp

spring.datasource.url=jdbc:postgresql://localhost:5432/clinicapp
spring.datasource.username=postgres
spring.datasource.password=mutadak@1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
